services:
#frontend
  # nextjs:
  #   container_name: nextjs
  #   image: nextjs:latest
  #   build:
  #     context: ./frontend
  #     dockerfile: nextjs.dockerfile
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - flaskapp
  #   develop:
  #     watch:
  #       - action: rebuild
  #         path: ./frontend/package.json
  #       - action: rebuild
  #         path: ./frontend/next.config.ts
  #       - action: rebuild
  #         path: ./frontend/app
  #       - action: rebuild
  #         path: ./frontend/public
#backend
  flaskapp:
    container_name: flaskapp
    image: flaskapp:latest
    build:
      context: ./backend
      dockerfile: flask.dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db
    develop:
      watch:
        - action: rebuild
          path: ./backend/app.py
        - action: rebuild
          path: ./backend/requirements.txt
        - action: rebuild
          path: ./backend/flask.dockerfile

#database
  db:
    container_name: db
    image: postgres:18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql

volumes:
  db_data: {}